[package]
name = "bigtools"
version = "0.1.3"
authors = ["Jack Huey <jackh726@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A library and associated tools for reading and writing bigwigs and bigbeds"
keywords = ["bigwig", "bio"]

[dependencies]
byteorder = "1.3.4"
byteordered = "0.5.0"
crossbeam-channel = "0.5.0"
crossbeam-utils = "0.8.0"
tempfile = "3.1.0"
futures = { version = "0.3.6", features = ["thread-pool"] }
parking_lot = { version = "0.11.0" }
serde = { version = "1.0", features = ["derive"] }
clap = "3.0.0-beta.2"
itertools = "0.9.0"
bincode = "1.3.1"
reqwest = { version = "0.10.8", optional = true }
tokio = { version = "0.3.0", optional = true, default-features = false, features = ["io-util", "rt", "rt-multi-thread"] }
libdeflater = "0.5.0"

[dev-dependencies]
rand = "0.6.5"

[profile.release]
lto = false
debug-assertions = true


[profile.dev]
opt-level = 3

[lib]
name = "bigtools"
path = "src/lib.rs"

[[bin]]
name = "test"
required-features = ["remote"]

[features]
default = ["remote"]
remote = ["reqwest", "tokio"]

