[package]
name = "bigwig2"
version = "0.1.0"
authors = ["Jack <jack.huey@umassmed.edu>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
byteordered = "0.4.0"
crossbeam = "0.7.0"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
tempfile = "3"
futures-preview = { version = "0.3.0-alpha.16", features = ["nightly", "async-await"] }
rand = "0.6.5"
parking_lot = { version = "0.7.1", features = ["nightly"] }

[profile.release]
debug = true
debug-assertions = true
overflow-checks = true

[profile.dev]
opt-level = 3

[lib]
name = "bigwig2"
path = "src/lib.rs"

[[bin]]
name = "writetest"
path = "src/write_test.rs"

[[bin]]
name = "readtest"
path = "src/read_test.rs"

[[bin]]
name = "mergetest"
path = "src/merge_test.rs"

