[package]
name = "bigwig2"
version = "0.1.0"
authors = ["Jack <jack.huey@umassmed.edu>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
flate2 = { version = "1.0", features = ["zlib"], default-features = false }
tempfile = "3"
futures-preview = { version = "0.3.0-alpha.13", features = ["compat"] }
tokio = {version = "0.1.0", features = ["async-await-preview"]}

[profile.release]
debug = true
